name: Test Hello-world API

on:
  push:
    branches:
      - playwright-api-testing-s3-reports-public-url

env:
  ROOT_PATH: '${{ github.workspace }}'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing dependencies
        run: npm install
        working-directory: ${{ env.ROOT_PATH }}

      - name: Installing Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ${{ env.ROOT_PATH }}

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  
          aws configure set default.output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Starting Server
        run: npm start
        working-directory: ${{ env.ROOT_PATH }}

      - name: Running tests
        run: npm test
        working-directory: '${{env.ROOT_PATH}}'
        continue-on-error: true

      - name: Store the test-results.json file in an S3 bucket for JSON Reports
        if: always()
        run: |
          aws s3 cp $GITHUB_WORKSPACE/test-results/test-results.json ${{vars.S3_URI}}

      - name: Generate public links to JSON reports stored in an S3 bucket.
        run: echo "${{vars.OBJECT_URL}}"