name: Test Hello-world API

on:
  push:
    branches:
      - playwright-api-testing-s3

env:
  ROOT_PATH: '${{ github.workspace }}'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing dependencies
        run: npm install
        working-directory: ${{ env.ROOT_PATH }}

      - name: Installing Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ${{ env.ROOT_PATH }}

      - name: Starting Server
        run: npm start
        working-directory: ${{ env.ROOT_PATH }}

      - name: Running tests
        run: npm test
        working-directory: ${{ env.ROOT_PATH }}
