name: Test Hello-world API

on:
  push:
    branches:
      - playwright-api-testing-s3-reports-public-url

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ROOT_PATH: '${{ github.workspace }}'
  REPORT_ID: '${{github.run_id}}'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing dependencies
        run: npm install
        working-directory: ${{ env.ROOT_PATH }}

      - name: Installing Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ${{ env.ROOT_PATH }}

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1  
          aws configure set default.output json
     
        
      - name: Starting Server
        run: npm start
        working-directory: ${{ env.ROOT_PATH }}

      - name: Running tests
        run: npm test
        working-directory: '${{env.ROOT_PATH}}'
        continue-on-error: true

      - name: Uploading test reports to Amazon S3
        if: always()
        run: |
          aws s3 cp "${{env.ROOT_PATH}}/playwright-report/index.html" s3://hello-world-api-testing-plt/playwright-report/report_${{env.REPORT_ID}}.html

      - name: URL of Playwright Report
        run: echo "https://hello-world-api-testing-plt.s3.us-east-1.amazonaws.com/playwright-report/report_${{env.REPORT_ID}}.html"

      - name: Generate Allure Reports
        run: npx allure generate --clean

      - name: Uploading Allure reports to S3
        run: |
          aws s3api put-object --bucket hello-world-api-testing-plt --key allure-reports/report_${{env.REPORT_ID}}/
          aws s3 sync ${{env.ROOT_PATH}}/allure-report s3://hello-world-api-testing-plt/allure-reports/report_${{env.REPORT_ID}}/

      - name: URL of Allure Report
        run: echo "https://hello-world-api-testing-plt.s3.us-east-1.amazonaws.com/allure-reports/report_${{env.REPORT_ID}}/index.html"